controller_list:
  - name: fake_niryo_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_niryo_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2
initial:  # Define initial robot poses per group
  - group: niryo_arm
    pose: home